version: 2.1

jobs:
  zero2prod-ci:
    docker:
      - image: cimg/rust:stable

    steps:
      - checkout

      - run:
          name: Install Rust components
          command: |
            rustup component add rustfmt
            rustup component add clippy

      - run:
          name: Install cargo tools
          command: |
            cargo install cargo-tarpaulin
            cargo install cargo-audit

      - restore_cache:
          keys:
            - cargo-cache-v1-{{ checksum "Cargo.lock" }}
            - cargo-cache-v1-

      - run:
          name: Cargo Check
          command: cargo check

      - run:
          name: Format Check
          command: cargo fmt -- --check

      - run:
          name: Clippy Lints
          command: cargo clippy -- -D warnings

      - run:
          name: Run Tests
          command: cargo test

      - run:
          name: Code Coverage
          command: cargo tarpaulin --ignore-tests

      - run:
          name: Security Audit
          command: cargo audit

      - save_cache:
          paths:
            - ~/.cargo
            - target
          key: cargo-cache-v1-{{ checksum "Cargo.lock" }}

workflows:
  version: 2
  rust-workflow:
    jobs:
      - zero2prod-ci